import type { Metadata } from "next";
import { Quicksand } from "next/font/google"; // Import Quicksand font
import "./globals.css";
import { FloatingNav } from "../components/ui/floating-navbar";

// Load the Quicksand font
const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        {" "}
        {/* Apply Quicksand as the default font */}
        {children}
      </body>
    </html>
  );
}
